//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfo
    {
        public int Id { get; set; }
        public string HomeAddress { get; set; }
        public Nullable<long> HomePhone { get; set; }
        public string OfficeAddress { get; set; }
        public long OfficePhone { get; set; }
        public string EmailAdd { get; set; }
        public Nullable<long> CellphoneNumber { get; set; }
    
        public virtual Physician Physician { get; set; }
    }
}
